name: Retrieve org_id

on:
  workflow_call:
    # Map the workflow outputs to job outputs
    outputs:
      org_id:
        description: "The first output string"
        value: ${{ jobs.get_org_id.outputs.org_id }}
  workflow_dispatch:
    inputs:
      TS_ORG_NAME:
        type: string
        description: 'ThoughtSpot org name (not org_id)'
        required: true
        default: 'Primary'

jobs:
  get_org_id:
    name: Generate output
    runs-on: ubuntu-latest
    # Map the job outputs to step outputs
    outputs:
      org_id: ${{ steps.step1.outputs.orgid }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install thoughtspot_rest_api 
        # if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Import TML to ThoughtSpot Org ${{ vars.TS_ORG_NAME }}
      env:
       TS_SERVER: ${{ secrets.TS_SERVER }}
       TS_SECRET_KEY: ${{ secrets.TS_SECRET_KEY }}
       TS_USERNAME: ${{ secrets.TS_INSTANCE_ADMIN_USERNAME }}
       TS_ORG_NAME: ${{ vars.TS_ORG_NAME }}
 
      run: |
        python .github/workflows/retrieve_org_id_from_org_name.py
        echo $ORG_ID
    - id: step1
      run: echo "orgid=$ORG_ID" >> $GITHUB_OUTPUT
